project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Ruoshui Xu"
  site-url: https://ruoshui-xu.github.io
  favicon: images/site-logo.jpg
  repo-url: https://github.com/ruoshui-xu/ruoshui-xu.github.io
    
  navbar: 
    background: "#1E4D2B"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Experience"
        href: experience.qmd
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: CV.pdf
      

format:
  html:
    theme: styles.scss
    toc: true           # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细